### PR TITLE
general code cleanup

### PR DESCRIPTION
**Pull request by flancast90**
Well, I said that I didn't have any time to help on this project, but I found some :). Here's some changes I've made:

- make more strongly typed
- change class to "clipboard"
- remove global vars, and pass within class instead
- better variable names
- fix infinite threading bug with thread creation in "while" loop
- continuous listening class to not block main thread
- CTRL+P auto-copies to next item in dict
- general optimization from ~100 to ~70 lines.

TODO:
- verify if paste function works. Pyautogui install issues on my PC, so I can't test that.
- work on GUI class. Possible add function to clipboard class to get dictionary.
- Find better keyboard command for Paste. CTRL+ALT+V+{NUM} is a bit clunky. Perhaps block the CTRL+V system call with ctypes module (need to research), and open the GUI to have user select value to paste from there.

Let me know of any questions!

### CODE REVIEW

**Comment by Reiningecho90** [comment]
I’ll check this out later today. I’ll test it out then add more comments.

**Review by Reiningecho90 — CHANGES_REQUESTED** [review]
Add number handling for copy function. For example try handling as:

if k.is_pressed(“ctrl+c”):
——# listen for a number press?
——if k.is_pressed(“1, 2, 3, 4, 5, 6, 7, 8, 9, 0,”):
————# normal handling

**Comment by Reiningecho90** [comment]
Added a new commit, @flancast90 can review it and make sure it works, then push.

**Review by Reiningecho90 — APPROVED** [review]
approved all changes, GUI will come later, this works terminal based. Will work on GUI today and make a pull.

**Comment by flancast90** [comment]
> Add number handling for copy function. For example try handling as:
> 
> if k.is_pressed(“ctrl+c”):
> ——# listen for a number press?
> ——if k.is_pressed(“1, 2, 3, 4, 5, 6, 7, 8, 9, 0,”):
> ————# normal handling

Alright, I added this feature and requested to merge with the PR. I changed around how you recommended to do it to use the same loop as was previously used for the paste check, which means the line count and readability is the same.

**Comment by Reiningecho90** [comment]
Let's push this for now, I'll reopen the request if anything adverse happens during testing later.

**Pull request merged**
